name: 114514

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main

    - name: 114514
      run: |
        cd /usr/local/lib/android/sdk/ndk/29.0.14206865/toolchains/llvm/prebuilt/linux-x86_64/bin/
        ls -l llvm-objcopy
        file llvm-objcopy
        bash llvm-objcopy --version
        bash llvm-objcopy --help
